language: node_js
sudo: false
node_js:
- '4'
branches:
  only:
  - master
addons:
  apt:
    sources: [ 'ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.5' ]
    packages: [ 'libstdc++6' ]
script:
  - git clone https://github.com/klokantech/gl-style-package-spec.git
  - cd gl-style-package-spec
  - bash ./task/deploy.sh
env:
  global:
    - secure: CJyjkCdY2uGsygno17U3PiG1x+tObL+hyMqb36e2iG0pKtmeEaThx+utIqZfXg4vES6PoablHaKUT7Qc/4n/O/ya6hDtuq5Ln3KkUUtAc9hFeG4whK5nEnF5o7LuDi3YL+EOrQaOl7QTH5qpUgFIP3lJ4O7rRvzyDpYlIdUVrqWZb+6+7nOcgMuZu0chhkHttZtDhhIVwzzUrBvlfe7+egykQrNdZa9jkioCR9Rvfe91mc5YnOFHx76ixjEqMYjGxyxbVP4S1qr1LynNCelzpwgVuqeE+Ygj5cXZw0+eCcjZBtFIjzcY+ap7jyevATW5QVZjEjjVTATOV0u+p0f57V/0p1iidgib8r6ct167rck3+VSlP5d0g/pLOOYPJDvRfitWTWQi+MsIEKksM8khoD3hOtMmxMeGVhsO7+LYtQBSkRfkzsGmLNBNo35x3Oew5f0tN6S/3vBew5lNputsvls2/it/HZDqebQt0bA10tOVmfj/BxCILWeD4/krZJE0Tjz89BGa0D/EX0BalOr8fZRVG9+9ewWl38IpPVEbeZ/Pm7w3XRvSeW97mdl4pb1hYBqCMno3x6iq8c58h0B7LySy061gsGoWL8cJyS69UhSdHHlYpeQIZKrG0EnmZn/a+gA2jk3I6urP5tABbxna7H54Guz7RKp0MEngU+1vnLw=
